### PR TITLE
Added JSONParser.js

### PR DESCRIPTION
**Pull request by coderextreme**

### CODE REVIEW

**Comment by andreasplesch** [comment]
Just to clarify: is this the first cut, untested version ?

**Comment by coderextreme** [comment]
Yes.   It should compile.

**Comment by coderextreme** [comment]
Except it's in a different folder now.   Hmm

**Comment by coderextreme** [comment]
Sorry if this is a repeat.   It should compile, but the folder structure
changed, so IDK.   Maybe put it under the main Parser folder

**Comment by create3000** [comment]
FYI: The next version of Titania can parse and generate JSON encoded X3D files.

**Comment by create3000** [comment]
There is a test file in `cobweb.js/tests/Components/Scripting/toXMLString.json`, not very representative but should include almost all statements and cases.

**Comment by create3000** [comment]
Would like to merge but cannot find JSONParser file.

**Comment by create3000** [comment]
There is another JSON test file, more simple, in the same folder `MURCIELAGO640.json` which should show a car with rotating wheels.

**Pull request merged**
